### ISSUE TITLE
Herper installation on Bioconductor 3.14

### ISSUE THREAD

**Issue by weizhouzh** [RockefellerUniversity/Herper#22]
I tried to install Herper following the codes and here is message I received from both R 4.1.0 and R4.1.3. 

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
Installing package(s) 'Herper'
Warning message:
In .inet_warning(msg) :
  package ‘Herper’ is not available for Bioconductor version '3.14'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Is there any other way I can install Herper on R or do I have other choice to manage Conda Packages? thanks a lot. 

New to the field.

**Comment by almeidasilvaf** [comment]
Hi, @weizhouzh 

I had the same problem a few weeks ago. Have you tried installing the package from GitHub?

```{r}
remotes::install_github("RockefellerUniversity/Herper")
```

**Comment by matthew-paul-2006** [comment]
Thanks @[almeidasilvaf](https://github.com/almeidasilvaf)

The GitHub install should work. It seems like there are some issues with Herper being built for mac systems at the moment through Bioconductor. I thought they were fixed, but obviously not. 

I'll look into this and get it fixed.

**Comment by kcamnairb** [comment]
I'm trying to install Herper on R 4.2.0 using `remotes::install_github("RockefellerUniversity/Herper")` and I'm getting this error:
  ```
checking for file ‘/local/bgfs/brian.mack/8075088/RtmpO0Dug7/remotes2df3b5b3939cc/RockefellerUniversity-Herper-caee478/DESCRIPTION’ (539ms)
─  preparing ‘Herper’:
E  checking DESCRIPTION meta-information ...
   Authors@R field gives more than one person with maintainer role:
     Matt Paul <matthew.paul.2006@gmail.com> [aut, cre] (<https://orcid.org/0000-0002-3020-7729>)
     Thomas Carroll <tc.infomatics@gmail.com> [aut, cre] (<https://orcid.org/0000-0002-0073-1714>)

   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'Herper' from GitHub:
  ! System command 'R' failed

```

**Comment by almeidasilvaf** [comment]
Same for me.

The package also does not install miniconda anymore. 

Such a pity. The package has never built on Linux and macOS the release 3.15 of Bioconductor, and we're already close to release 3.16. 

As a package developer and maintainer myself, I understand that bugs show up, but leaving these big bugs unfixed for so long will eventually make all users abandon the package.

**Comment by matthew-paul-2006** [comment]
We've been having a few issues with the new arm64 chip, that are quite inconsistent and hard for us to debug as none of us have this new chip. We think we have all the bugs mentioned above fixed, but if anyone is still having a problem please start a new issue with full command and error message. Thanks!
